//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/InputSystem/Input.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Input : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Input()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Input"",
    ""maps"": [
        {
            ""name"": ""PlayerInput"",
            ""id"": ""611ba759-29ba-4739-80ec-234383cab5fd"",
            ""actions"": [
                {
                    ""name"": ""Test"",
                    ""type"": ""Button"",
                    ""id"": ""d2914dc9-f6cb-4056-8522-c3b9608eea0c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TargetEntity"",
                    ""type"": ""Button"",
                    ""id"": ""4883b536-5140-45cd-9e22-ad54940a90fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""eaac2af1-32be-4350-b94d-47dec260b4e9"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Test"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b1a3a29-f40f-484e-97ef-a497deebbd24"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TargetEntity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerInput
        m_PlayerInput = asset.FindActionMap("PlayerInput", throwIfNotFound: true);
        m_PlayerInput_Test = m_PlayerInput.FindAction("Test", throwIfNotFound: true);
        m_PlayerInput_TargetEntity = m_PlayerInput.FindAction("TargetEntity", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerInput
    private readonly InputActionMap m_PlayerInput;
    private IPlayerInputActions m_PlayerInputActionsCallbackInterface;
    private readonly InputAction m_PlayerInput_Test;
    private readonly InputAction m_PlayerInput_TargetEntity;
    public struct PlayerInputActions
    {
        private @Input m_Wrapper;
        public PlayerInputActions(@Input wrapper) { m_Wrapper = wrapper; }
        public InputAction @Test => m_Wrapper.m_PlayerInput_Test;
        public InputAction @TargetEntity => m_Wrapper.m_PlayerInput_TargetEntity;
        public InputActionMap Get() { return m_Wrapper.m_PlayerInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerInputActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerInputActions instance)
        {
            if (m_Wrapper.m_PlayerInputActionsCallbackInterface != null)
            {
                @Test.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnTest;
                @Test.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnTest;
                @Test.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnTest;
                @TargetEntity.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnTargetEntity;
                @TargetEntity.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnTargetEntity;
                @TargetEntity.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnTargetEntity;
            }
            m_Wrapper.m_PlayerInputActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Test.started += instance.OnTest;
                @Test.performed += instance.OnTest;
                @Test.canceled += instance.OnTest;
                @TargetEntity.started += instance.OnTargetEntity;
                @TargetEntity.performed += instance.OnTargetEntity;
                @TargetEntity.canceled += instance.OnTargetEntity;
            }
        }
    }
    public PlayerInputActions @PlayerInput => new PlayerInputActions(this);
    public interface IPlayerInputActions
    {
        void OnTest(InputAction.CallbackContext context);
        void OnTargetEntity(InputAction.CallbackContext context);
    }
}
